#!/usr/bin/bash
# Get interface address from user
echo "Setting up GNS3..."
echo "Available ethernet interfaces:"
# host_interface=$(ip addr show | awk '$2 ~ /^(em|en|et).*[0-9]:/ {print substr($2, 1, length($2)-1)}')
choices=$(ip addr show | awk '$2 ~ /^(em|en|et).*[0-9]:/ {print substr($2, 1, length($2)-1)}')
echo "$choices"
while :
do
  read -r -p "Enter an ethernet interface for GNS3 to use: " host_interface
  valid="^(em|en|et).*[0-9]$"
  if [[ $host_interface =~ $valid ]] && [[ "$choices" == *"$host_interface"* ]];
  then
      echo "Good to go!"
      break
  else
      echo "Invalid interface name. Please try again."
  fi
done
# sudo ip tuntap add tap0 mode tap # Add the tap device
# sudo ifconfig tap0 0.0.0.0 promisc up # Configure the tap
sudo ifconfig "$host_interface" 0.0.0.0 promisc up # Zero out the selected Ethernet connection
sudo brctl addbr br0 # Create the bridge
# sudo brctl addif br0 tap0 # Add the tap to the bridge
sudo brctl addif br0 "$host_interface" # Add the selected Ethernet connection to the bridge
sudo ifconfig br0 up # Start the bridge
sudo ifconfig br0 192.168.1.1/24 # Configure the bridge
echo
echo -e "Network interface configuration:"
ifconfig # Verify the devices exist
echo
echo -e "Bridge information:"
sudo brctl show br0 # Verify the bridge is set up
echo
echo -e "Starting GNS3..."
gns3 # Start GNS3
# Upon exit from GNS3, reset the default Ethernet connection to access the Internet
sudo ifconfig br0 down # Stop the bridge
sudo brctl delif br0 "$host_interface" # Remove the default Ethernet connection from the bridge
# sudo brctl delif br0 tap0 # Remove the tap from the bridge
sudo brctl delbr br0 # Delete the bridge
# sudo ifconfig tap0 down # Stop the tap
# sudo ip link delete tap0 # Delete the tap
# Reset the default Ethernet connection
echo
echo -e "Resetting the network (please wait 30 seconds...)"
sudo ifconfig "$host_interface" -promisc
# sudo /etc/init.d/network restart
sudo systemctl restart network # Check your OS; may use service networking restart 
sleep 30
sudo systemctl status network
ifconfig # Verify the result
echo -e "Script complete. Have a nice day."
