#!/usr/bin/bash
echo "Setting up GNS3..."
# Get sudo password
read -r -s -p "[sudo] sudo password for $(whoami): " s_pass
echo

# Create a dummy interface
echo "$s_pass" | sudo -S modprobe dummy
sudo ip link add eth2 type dummy
# Ensure fake MAC address starts with an even octet
sudo ifconfig eth2 hw ether 12:FE:34:DC:56:BA
sudo ip link set dev eth2 up
host_interface=eth2

echo "Configuring the network..."
# Configure the bridge
sudo ip link add br0 type bridge &> /dev/null # Create the bridge
sudo ip address replace 192.168.1.1/24 dev br0 # Set the gateway IP address
sudo ip link set br0 up # Enable the bridge

# Configure the tap
sudo ip tuntap add tap0 mode tap # Create the tap
sudo ip link set tap0 up # Enable the tap
sudo ip link set tap0 master br0 # Connect the tap to the bridge

# Add another tap, for flexibility
sudo ip tuntap add tap1 mode tap # Create the tap
sudo ip link set tap1 up # Enable the tap
sudo ip link set tap1 master br0 # Connect the tap to the bridge

# Configure the isolated Ethernet network adapter
sudo ip address flush dev "$host_interface" # Clear out any old adapter IP address
sudo ip link set "$host_interface" up # Enable the adapter
sudo ip link set "$host_interface" master br0 # Connect the adapter to the bridge
sleep 3
sudo ip address replace 192.168.1.10/24 dev "$host_interface" # Set the adapter IP address

# Display configuration
echo
echo -e "Network interface configuration:"
ip address show
echo
echo -e "Bridge information:"
sudo brctl show br0 # Verify the bridge is set up
echo
echo -e "Starting GNS3..."
gns3 # Start GNS3

# After GNS3 closes, shutdown the connection and the dummy interface
echo
echo -e "Resetting the network..."
echo "$s_pass" | sudo -S ip link set "$host_interface" down &> /dev/null
sudo ip link set tap1 down
sudo ip link delete tap1
sudo ip link set tap0 down
sudo ip link delete tap0
sudo ip link set br0 down
sudo ip link delete br0
sudo ip addr del 192.168.1.10/24 brd + dev eth2 label eth2:0
sudo ip link delete eth2 type dummy
sudo rmmod dummy
echo
echo -e "Network interface configuration:"
ip address show
echo
echo -e "Script complete. Have a nice day."
