#!/usr/bin/bash
echo -e "Setting up GNS3..."
echo -e "Using:"
cat /etc/centos-release
echo -e "Updating CentOS"
sudo yum -y update
# Install Python 3 and pip
sudo yum -y install python3 # Also installs python3-setuptools
sudo python3 -m pip install --upgrade pip
sudo python3 -m ensurepip
sudo yum -y install python3-devel
sudo yum -y install python3-tools
# Install pip support for Python 2
sudo yum -y install python-pip
# Install Git
sudo yum -y install git
# Install GNS3 dependencies
sudo yum -y groupinstall "Development Tools" # Only need gcc to run GNS3, but we will need the other tools later
sudo yum -y install elfutils-libelf-devel # For Dynamips
sudo yum -y install libpcap-devel # For Dynamips
sudo yum -y install cmake # For Dynamips, VCPS, and ubridge
sudo yum -y install glibc-static # For VCPS
# Install Qt GUI library
sudo yum -y install qt5-qtbase
sudo yum -y install qt5-qtbase-devel
sudo yum -y install qt5-qtsvg
sudo yum -y install qt5-qtsvg-devel
# Install xterm, one of the consoles used by GNS, and resize its output
sudo yum -y install xterm
echo -e "! Use a truetype font and size.\nxterm*faceName: Monospace\nxterm*faceSize: 12" > ~/.Xresources
sudo xrdb -merge ~/.Xresources
# Install GNS3
sudo python3 -m pip install gns3-server --upgrade
sudo python3 -m pip install gns3-gui --upgrade
sudo python3 -m pip install sip # For PyQT; used to bind C++ classes with Python
sudo python3 -m pip install pyqt5
sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm # needed to install PuTTY and qemu
sudo yum -y install putty # Get from epel
# KVM: A Linux kernel module that interacts with the virtualization features of the processor.
# QEMU: Virtualization software that emulates virtual processors and peripherals.
# QEMU-KVM: Type 1 hypervisor that runs in kernel space and QEMU: type 2 hypervisor that runs in user space
sudo yum -y install qemu # Get from epel / Not qemu-kvm https://fedoraproject.org/wiki/How_to_use_qemu
# Install the Dynamips Cisco Emulator
cd /tmp || exit
git clone https://github.com/GNS3/dynamips.git
cd dynamips || exit
mkdir build
cd build/ || exit
cmake .. -DDYNAMIPS_CODE=stable
make
sudo make install
# Install the Virtual PC Simulator (vpcs)
cd /tmp || exit
sudo yum -y install svn
svn checkout http://svn.code.sf.net/p/vpcs/code/trunk vpcs
cd vpcs/src || exit
./mk.sh 64
sudo install -m 755 vpcs /usr/local/bin
# Install ubridge to connect Ethernet, TAP interfaces, and UDP tunnels, as well as capture packets.
cd /tmp || exit
git clone https://github.com/GNS3/ubridge.git
cd ubridge || exit
make
sudo make install
cd ~ || exit
# Get router image and configuration file
wget -P ~/GNS3/images/IOS http://tfr.org/cisco-ios/37xx/3745/c3745-adventerprisek9-mz.124-25d.bin # Cisco 3745
wget -P ~/GNS3/images/IOS http://tfr.org/cisco-ios/7200/c7200-a3jk9s-mz.124-25d.bin # Cisco 7206
# Used to create interfaces to connect the host to GNS3
sudo yum -y install bridge-utils
# Install modules to control interactions with external devices
sudo yum -y install pexpect # (For Python 2.7+)
sudo python3 -m pip install pexpect # (For Python 3.6+)
sudo yum -y install paramiko
sudo yum -y install ansible
# Install Selenium for Firefox
sudo yum -y install firefox
pip install selenium
wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz --directory-prefix ~/Downloads
sudo tar -xzf ~/Downloads/geckodriver-v0.30.0-linux64.tar.gz -C /usr/local/bin/
# Get the script that creates a tap/loopback interface in Linux and launches GNS3
wget -P ~/ https://raw.githubusercontent.com/garciart/Automation/master/gns3_run
# Make the start-up script executable and place it in /usr/bin
sudo chmod 755 ~/gns3_run
sudo mv ~/gns3_run /usr/bin/
# Required for the labs
sudo yum -y install telnet
sudo yum -y install tftp tftp-server*
sudo yum -y install ntp
sudo yum -y install vsftpd
sudo yum -y install httpd
# Install SSH support, including ssh, scp, sftp, sshd, ssh-keygen, etc.
sudo yum -y install openssh
sudo yum -y install openssh-clients
sudo yum -y install openssh-server
sudo yum -y install mod_ssl openssl
sudo mkdir -p /var/lib/tftpboot
sudo chmod 777 /var/lib/tftpboot
# Optional - Modify vimrc file
echo -e "\"My preferred vim defaults\nset tabstop=4\nset softtabstop=4\nset expandtab\nset shiftwidth=4\nset smarttab" > ~/.vimrc
echo -e "Setup complete. Review the output of this script and fix any errors.\nRemember to reboot before starting GNS3."
