#!/usr/bin/bash
# Get interface address from user
echo "Setting up GNS3..."
echo "Available Ethernet interfaces:"
# host_interface=$(ip addr show | awk '$2 ~ /^(em|en|et).*[0-9]:/ {print substr($2, 1, length($2)-1)}')
choices=$(ip addr show | awk '$2 ~ /^(em|en|et).*[0-9]:/ {print substr($2, 1, length($2)-1)}')
echo "$choices"
while :
do
  read -r -p "Enter an Ethernet interface for GNS3 to use: " host_interface
  valid="^(em|en|et).*[0-9]$"
  if [[ $host_interface =~ $valid ]] && [[ "$choices" == *"$host_interface"* ]];
  then
      echo "Good to go!"
      break
  else
      echo "Invalid interface name. Please try again."
  fi
done
# Get sudo password
read -r -s -p "[sudo] sudo password for $(whoami): " s_pass
echo
echo "Configuring the network..."
# Configure the bridge
echo "$s_pass" | sudo -S ip link add br0 type bridge &> /dev/null # Create the bridge
sudo ip address replace 192.168.1.1/24 dev br0 # Set the gateway IP address
sudo ip link set br0 up # Enable the bridge

# Configure the tap
sudo ip tuntap add tap0 mode tap # Create the tap
sudo ip link set tap0 up # Enable the tap
sudo ip link set tap0 master br0 # Connect the tap to the bridge

# Configure the isolated Ethernet network adapter
sudo ip address flush dev "$host_interface" # Clear out any old adapter IP address
sudo ip link set "$host_interface" up # Enable the adapter
sudo ip link set "$host_interface" master br0 # Connect the adapter to the bridge
sleep 3
sudo ip address replace 192.168.1.10/24 dev "$host_interface" # Set the adapter IP address

# Display configuration
echo
echo -e "Network interface configuration:"
ip address show
echo
echo -e "Bridge information:"
sudo brctl show br0 # Verify the bridge is set up
echo
echo -e "Starting GNS3..."
gns3 # Start GNS3

# After GNS3 closes, shutdown the connection
echo
echo -e "Resetting the network..."
echo "$s_pass" | sudo -S ip link set "$host_interface" down &> /dev/null
sudo ip link set tap0 down
sudo ip link delete tap0
sudo ip link set br0 down
sudo ip link delete br0
echo
echo -e "Network interface configuration:"
ip address show
echo
echo -e "Script complete. Have a nice day."
